apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dotnet-todos-api
  labels:
    app.kubernetes.io/part-of: dotnet-todos-api
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1658237551119406091"
    kapp.k14s.io/association: v1.f1bca9a4d74577070d892a5adc240403
    app.kubernetes.io/component: run
    carto.run/workload-name: dotnet-todos-api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.apps.tanzu.vmware.com/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kapp.k14s.io/identity: v1;dotnet-todos/carto.run/Workload/dotnet-todos-api;carto.run/v1alpha1
        kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"labels":{"app.kubernetes.io/part-of":"dotnet-todos-api","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web","kapp.k14s.io/app":"1658237551119406091","kapp.k14s.io/association":"v1.f1bca9a4d74577070d892a5adc240403"},"name":"dotnet-todos-api","namespace":"dotnet-todos"},"spec":{"env":[{"name":"ConnectionStrings__DefaultConnection","valueFrom":{"secretKeyRef":{"key":"connection-string","name":"api-db-credentials"}}}],"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1"}},{"name":"gitops_repository_name","value":"gitops-dotnet-todos"},{"name":"language","value":"dotnet"}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/jeffellin/dotnet-employee-todo-list-api.git"}}}}'
        kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: dotnet-todos-api
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: dotnet-todos-api
        kapp.k14s.io/app: "1658237551119406091"
        kapp.k14s.io/association: v1.f1bca9a4d74577070d892a5adc240403
    spec:
      containers:
      - env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              key: connection-string
              name: api-db-credentials
        image: harbor.one.appref.end2end.link/tap/sc/dotnet-todos-api-dotnet-todos@sha256:75f28d9a7ee357a96e5d26790f1ad1544494e6de399c045c17f3e3953e650157
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

